steps:
    - name: 'ejangi/hugo'
      id: Build
      dir: 'public'
      volumes: 
        - name: '.'
          path: '/src/'
      args: ['hugo', '--minify']
    - name: 'gcr.io/cloud-builders/gsutil'
      id: Deploy
      args: ['cp', '-r', 'public/*', 'gs://ejangi.com/']