steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/npm'
  id: Install Dependencies
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  id: Install Bower and Gulp
  args: ['install','-g','bower','gulp']

- name: 'gcr.io/cloud-builders/npm'
  id: Build
  args: ['run','build']

- name: 'gcr.io/cloud-builders/npm'
  id: Test
  args: ['run','test']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy
  args: ['cp', '-r', 'dist/**', 'gs://ejangi.com/']
