steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'install'

- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'install'
  - '-g'
  - 'bower'
  - 'gulp'

- name: 'gcr.io/cloud-builders/npm'
  args:
  - 'run'
  - 'build'

artifacts:
  objects:
    location: 'gs://artifacts.lunar-nuance-251922.appspot.com'
    paths: ['dist']
