baseURL = "https://ejangi.com/"
languageCode = "en-au"
title = "James Angus"
theme = "ejangi"
googleAnalytics = ""

[params]
    EmailAddress = "james@ejangi.com"
    PGPKey = "images/publickey.james@ejangi.com.asc"
    ProfilePhoto = "images/profile-photo.png"
    CorePhilosophy = "Technology should work hard for people, not the other way around"
    CurrentJobTitle = "Service Evolution Manager"
    Location = "Brisbane, Australia"
    Expertise = ["Business Analysis", "Data Analysis", "Design & Programming"]
    LinkedIn = "https://au.linkedin.com/in/ejangi"
    Twitter = "https://twitter.com/ejangi"
    Github = "https://github.com/ejangi"
    Trailblazer = "https://trailblazer.me/id/ejangi"
    pieColors = [ "#4A3FC9", "#C09F66", "#3A3D46", "#777777", "#FFFFFF"]
    CopyrightNotice = "&copy; James Angus 2020. View source on [Github](https://github.com/ejangi/ejangi.com)."

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$",".png$",".gif$",".css$",".js$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "gcs"
URL = "gs://ejangi.com"

[[deployment.matchers]]
#  Cache static assets for 1 years.
pattern = "^.+\\.(js|css|svg|ttf)$"
# cacheControl = "max-age=31557600, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
# cacheControl = "max-age=31557600, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true