baseURL = "https://ejangi.com/"
languageCode = "en-au"
title = "James Angus"
theme = "ejangi"
googleAnalytics = ""

[params]
    EmailAddress = "james@ejangi.com"
    PGPKey = "images/publickey.james@ejangi.com.asc"
    ProfilePhoto = "images/profile-photo.png"
    CorePhilosophy = "Technology should work hard for people, not the other way around"
    CurrentJobTitle = "Service Evolution Manager"
    Location = "Brisbane, Australia"
    Expertise = ["Business Analysis", "Data Analysis", "Design & Programming"]
    LinkedIn = "https://au.linkedin.com/in/ejangi"
    Twitter = "https://twitter.com/ejangi"
    Github = "https://github.com/ejangi"
    Trailblazer = "https://trailblazer.me/id/ejangi"