baseURL = "https://ejangi.com/"
languageCode = "en-au"
title = "James Angus"
theme = "ejangi"
googleAnalytics = "UA-12314225-1"

[params]
    description = "James Angus is a Brisbane (Australia) based Business Analyst and Developer."
    keywords = ["James Angus", "ejangi", "Brisbane", "Queensland", "Australia", "developer", "business analyst", "technical", "salesforce", "integration", "marketing cloud", "website", "guitarist"]
    mixPanelID = "1b559cf463eb9172e36fc351203057a4"
    EmailAddress = "james@ejangi.com"
    PGPKey = "images/publickey.james@ejangi.com.asc"
    ProfilePhoto = "images/profile-photo.png"
    CorePhilosophy = "Technology should work hard for people, not the other way around"
    CurrentJobTitle = "Service Evolution Manager"
    Location = "Brisbane, Australia"
    Expertise = ["Business Analysis", "Data Analysis", "Design & Programming"]
    LinkedIn = "https://au.linkedin.com/in/ejangi"
    Twitter = "https://twitter.com/ejangi"
    Github = "https://github.com/ejangi"
    Trailblazer = "https://trailblazer.me/id/ejangi"
    pieColors = [ "#4A3FC9", "#C09F66", "#3A3D46", "#777777", "#FFFFFF"]
    CopyrightNotice = "&copy; James Angus 2020. View source on [Github](https://github.com/ejangi/ejangi.com)."