version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3001:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"